name: Device Automation Services

on:
  push:
    tags:
      - "rel/das/*.*.*.*"
      - "dev/das/*.*.*.*"
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches:
    - develop

  workflow_dispatch:

jobs:
  devatserv-gui:
    name: DevAtServ's GUI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./python-microservice-base/MicroserviceBase/MicroserviceManagerGUI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone python-microservice-base
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'htv3hc/feat/release-microservice-base-gui'
          owner: 'test-fullautomation'
          repository: 'python-microservice-base'

      - name: Run npm install
        run: npm install

      - name: Run npm dist
        run: |
          npm run dist
    
      - name: Upload Ubuntu artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: das-gui-artifact-deb
          path: ./python-microservice-base/MicroserviceBase/MicroserviceManagerGUI/dist/*.deb

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: das-gui-artifact-exe
          path: ./python-microservice-base/MicroserviceBase/MicroserviceManagerGUI/dist/*.exe

      - name: Download and compress rabbitmq image for Windows
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker pull rabbitmq:3.13-management
          docker image save --output rabbitmq.tar.gz rabbitmq

      - name: Upload compressed image as artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq-image
          path: ./python-microservice-base/MicroserviceBase/MicroserviceManagerGUI/rabbitmq.tar.gz

  build-devatserv-liunx:
    name: DevAtServ tool Linux
    runs-on: ubuntu-latest
    needs: [ devatserv-gui ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download DevAtServ's GUI on Unbuntu
        uses: actions/download-artifact@v4
        with:
          name: das-gui-artifact-deb

      - name: Starting all services
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Build DevAtServ
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: devatserv-linux-package
          path: output_Linux/*.deb


  build-devatserv-windows:
    name: DevAtServ tool Windows
    runs-on: windows-latest
    needs: [ devatserv-gui ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download DevAtServ's GUI on Windows
        uses: actions/download-artifact@v4
        with:
          name: das-gui-artifact-exe

      - name: Download compressed image artifact
        uses: actions/download-artifact@v4
        with:
          name: rabbitmq-image

      - name: Load Docker image from tar file
        run: docker load -i rabbitmq.tar.gz
      
      - name: Starting all services
        shell: bash
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Build DevAtServ
        shell: bash
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Exe package
        uses: actions/upload-artifact@v4
        with:
          name: devatserv-windows-package
          path: output_Windows/*.exe