name: Device Automation Services

on:
  push:
    branches:
    - develop

  pull_request:
    branches:
    - develop

  workflow_dispatch:

jobs:
  build-devatserv:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Starting all services
        run: ./install.sh

      - name: Extract all services into images
        run: |
          docker image save --output devarserv_cleware-service.tar.gz devatserv_cleware-service
          docker image save --output devarserv-service-base.tar.gz multirepo_service-base
          mkdir -p ./build/storage
          mv devarserv-cleware-service.tar.gz devarserv-service-base.tar.gz ./build/storage
          ls -la ./build/storage
  
      - name: Build DevAtServ
        run: ./build.sh

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: devatserv-linux-package
          path: output_lx/*.deb