name: Device Automation Services

on:
  push:
    branches:
    - develop

  pull_request:
    branches:
    - develop

  workflow_dispatch:

jobs:
  build-devatserv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Starting all services
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Extract all services into images
        run: |
          docker images
          docker image save --output devarserv-cleware-service.tar.gz devatserv-cleware-service
          docker image save --output devarserv-service-base.tar.gz devatserv-service-base
          docker image save --output rabbitmq.tar.gz rabbitmq
          mv devarserv-cleware-service.tar.gz devarserv-service-base.tar.gz rabbitmq.tar.gz ./build/Linux/opt/devatserv/share/storage
          chmod 777 ./build/Linux/opt/devatserv/share/storage/*
  
      - name: Build DevAtServ
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: devatserv-linux-package
          path: output_lx/*.deb